---
# tasks file for tower_project_project_promote
- name: Step 1 - Create Project
  vars:
    # proj_scm_cred: 6
    # proj_scm_cred_name: 
    proj_desc: "{{ item.description }}"
    proj_scm_cache_to: "{{ item.scm_update_cache_timeout }}"
    proj_scm_update_on_launch: "{{ item.scm_update_on_launch }}"
    proj_scm_clean: "{{ item.scm_clean }}"
    proj_scm_type: "{{ item.scm_type }}"
    proj_scm_delete_on_update: "{{ item.scm_delete_on_update }}"
    proj_scm_url: "{{ item.scm_url }}"
    proj_scm_release: "{{ item.scm_branch }}"
    proj_timeout: "{{ item.timeout }}"
    proj_name: "{{ item.name }}"
  uri:
    method: POST
    headers:
      Authorization: "{{ auth }}"
    status_code: 201
    url: "{{ target }}/v2/organizations/{{ organization.id }}/projects/"
    body_format: json
    body: "{{ payload_project }}"
    return_content: yes
  register: create_proj_res
  loop: "{{ promotion_content }}"

- name: Present Result
  debug:
    msg: "{{ create_proj_res.json }}"

- name: Step 2 - updting proj_obj reference to reflect new values
  set_fact:
    proj_obj: "{{ create_proj_res.json }}"